-- En PostgreSQL, la creación de la base de datos y el usuario se ejecutan de forma separada 
-- o mediante herramientas de administración (pgAdmin, psql). 
-- Es recomendable ejecutar estas dos líneas primero si actúas como superusuario:
-- CREATE USER facturacion WITH PASSWORD 'usuario';
-- CREATE DATABASE taller OWNER facturacion;

-- A partir de aquí, el script asume que estás conectado a la base de datos 'taller'

-- Eliminar tablas si existen (respetando el orden de dependencias por claves foráneas)
DROP TABLE IF EXISTS conceptopresupuesto;
DROP TABLE IF EXISTS presupuesto;
DROP TABLE IF EXISTS conceptonota;
DROP TABLE IF EXISTS nota;
DROP TABLE IF EXISTS conceptoalbaran;
DROP TABLE IF EXISTS albaran;
DROP TABLE IF EXISTS conceptofactura;
DROP TABLE IF EXISTS factura;
DROP TABLE IF EXISTS cliente;
DROP TABLE IF EXISTS usuario;
DROP TYPE IF EXISTS tipo_usuario_enum;

-- -----------------------------------------------------
-- Tipo ENUM para los roles de usuario
-- -----------------------------------------------------
CREATE TYPE tipo_usuario_enum AS ENUM ('Admin', 'usuario', 'cliente');
-- -----------------------------------------------------
-- Table usuario
-- -----------------------------------------------------
CREATE TABLE usuario (
  id SERIAL, -- Cambiado de GENERATED BY DEFAULT AS IDENTITY a SERIAL
  nombre VARCHAR(250) NULL DEFAULT NULL,
  usuario VARCHAR(150) NULL DEFAULT NULL,
  password VARCHAR(500) NULL DEFAULT NULL,
  email VARCHAR(250) NULL DEFAULT NULL,
  tipoUsuario tipo_usuario_enum NOT NULL DEFAULT 'usuario',
  fechaNacimiento DATE NULL DEFAULT NULL,
  fechaEliminacion TIMESTAMP NULL DEFAULT NULL,
  imagen BYTEA NULL DEFAULT NULL,
  PRIMARY KEY (id)
);

-- -----------------------------------------------------
-- Table cliente
-- -----------------------------------------------------
CREATE TABLE cliente (
  id SERIAL, -- Cambiado a SERIAL
  NIF VARCHAR(15) NOT NULL,
  razonsocial VARCHAR(100),
  calle VARCHAR(50),  
  numero VARCHAR(50),
  piso VARCHAR(10),
  poblacion VARCHAR(30),
  provincia VARCHAR(30),
  CP INTEGER,
  telefono VARCHAR(50),
  observaciones VARCHAR(160),
  PRIMARY KEY (id)
);

-- -----------------------------------------------------
-- Table factura
-- -----------------------------------------------------
CREATE TABLE factura (
  id SERIAL, -- Cambiado a SERIAL
  numerofactura VARCHAR(15) NOT NULL,
  fecha DATE,
  iva REAL,                                     
  numerocliente INTEGER NOT NULL,
  pagado BOOLEAN,
  PRIMARY KEY (id),
  CONSTRAINT fk_factura_cliente
    FOREIGN KEY (numerocliente) REFERENCES cliente(id)
    ON UPDATE CASCADE ON DELETE RESTRICT
);
    
-- -----------------------------------------------------
-- Table conceptofactura
-- -----------------------------------------------------
CREATE TABLE conceptofactura (
  numeroconcepto INTEGER NOT NULL,
  idfactura INTEGER NOT NULL,
  descripcion VARCHAR(100),
  cantidad REAL,
  preciounidad REAL,
  descuento REAL,
  PRIMARY KEY (numeroconcepto, idfactura),
  CONSTRAINT fk_concepto_factura
    FOREIGN KEY (idfactura) REFERENCES factura(id)
    ON UPDATE CASCADE ON DELETE RESTRICT
);
    
-- -----------------------------------------------------
-- Table presupuesto
-- -----------------------------------------------------
CREATE TABLE presupuesto (
  id SERIAL, -- Cambiado a SERIAL
  numeropresupuesto VARCHAR(15) NOT NULL,
  fecha DATE,
  iva REAL,
  numerocliente INTEGER NOT NULL,
  aceptado BOOLEAN,
  PRIMARY KEY (id),
  CONSTRAINT fk_presupuesto_cliente
    FOREIGN KEY (numerocliente) REFERENCES cliente(id)
    ON UPDATE CASCADE ON DELETE RESTRICT
);
    
-- -----------------------------------------------------
-- Table conceptopresupuesto
-- -----------------------------------------------------
CREATE TABLE conceptopresupuesto (    
  numeroconpresup INTEGER NOT NULL,
  idpresupuesto INTEGER NOT NULL,
  descripcion VARCHAR(100),
  cantidad REAL,
  preciounidad REAL,
  descuento REAL,
  PRIMARY KEY (numeroconpresup, idpresupuesto),
  CONSTRAINT fk_concepto_presupuesto
    FOREIGN KEY (idpresupuesto) REFERENCES presupuesto(id)
    ON UPDATE CASCADE ON DELETE RESTRICT
);

-- -----------------------------------------------------
-- Tabla notas
-- -----------------------------------------------------
CREATE TABLE nota (
  id SERIAL, -- Cambiado a SERIAL
  numeronota VARCHAR(15) NOT NULL,
  fecha DATE,
  iva REAL,                                     
  numerocliente INTEGER NOT NULL,
  aceptado BOOLEAN,
  PRIMARY KEY (id),
  CONSTRAINT fk_nota_cliente
    FOREIGN KEY (numerocliente) REFERENCES cliente(id)
    ON UPDATE CASCADE ON DELETE RESTRICT
);
    
-- -----------------------------------------------------
-- Tabla conceptonota
-- -----------------------------------------------------
CREATE TABLE conceptonota (
  numeronota INTEGER NOT NULL,
  idnota INTEGER NOT NULL,
  descripcion VARCHAR(100),
  cantidad REAL,
  preciounidad REAL,
  descuento REAL,
  PRIMARY KEY (numeronota, idnota),
  CONSTRAINT fk_concepto_nota
    FOREIGN KEY (idnota) REFERENCES nota(id)
    ON UPDATE CASCADE ON DELETE RESTRICT
);

-- -----------------------------------------------------
-- Tabla Albarán
-- -----------------------------------------------------
CREATE TABLE albaran (
  id SERIAL, -- Cambiado a SERIAL
  numeroalbaran VARCHAR(15) NOT NULL,
  fecha DATE,
  iva REAL,                                     
  numerocliente INTEGER NOT NULL,
  pagado BOOLEAN,
  PRIMARY KEY (id),
  CONSTRAINT fk_albaran_cliente
    FOREIGN KEY (numerocliente) REFERENCES cliente(id)
    ON UPDATE CASCADE ON DELETE RESTRICT
);
    
-- -----------------------------------------------------
-- Tabla conceptoalbaran
-- -----------------------------------------------------
CREATE TABLE conceptoalbaran (
  numeroalbaran INTEGER NOT NULL,
  idalbaran INTEGER NOT NULL,
  descripcion VARCHAR(100),
  cantidad REAL,
  preciounidad REAL,
  descuento REAL,
  PRIMARY KEY (numeroalbaran, idalbaran),
  CONSTRAINT fk_concepto_albaran
    FOREIGN KEY (idalbaran) REFERENCES albaran(id)
    ON UPDATE CASCADE ON DELETE RESTRICT
);

ALTER TABLE factura
ADD CONSTRAINT uq_factura_numerofactura UNIQUE (numerofactura);

ALTER TABLE presupuesto
ADD CONSTRAINT uq_presupuesto_numeropresupuesto UNIQUE (numeropresupuesto);

ALTER TABLE nota
ADD CONSTRAINT uq_nota_numeronota UNIQUE (numeronota);

ALTER TABLE albaran
ADD CONSTRAINT uq_albaran_numeroalbaran UNIQUE (numeroalbaran);


-- Permisos para el usuario (se ejecutan sobre el esquema public en Postgres)
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO facturacion;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO facturacion;